---
spring:
  profiles:
    active: dev
  h2:
    console:
      enabled: true
      path: /console
  datasource:
    url: jdbc:h2:file:~/h2/testdb
  mail:
    to: "Vagram Sayadov <sayadov@gmail.com>"
    host: smtp.gmail.com
    port: 587
    username: kogelet@gmail.com
    password: Kogelet1983
    protocol: smtp
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      starttls.required: true
      ssl.trust: smtp.gmail.com
      connectiontimeout: 5000
      timeout: 5000
      writetimeout: 5000
ssmailer:
  floorsException: 1
  riga:
    maxNumberRooms: 2
    pricePerMeter: 1200
    buildingTypes: 119.,467.,Jaun.
  balozi:
    maxNumberRooms: 3
    pricePerMeter: 1200
    price:
    buildingTypes: Jaun.

---
spring:
  profiles: dev
logging:
 level:
  root: ERROR
  org.springframework.web: ERROR
  com.sun.mail.smtp: DEBUG
  com.ssparser: ERROR
ssparser:
  cronTime: "0 * * * * *"

---
spring:
 profiles: prod
logging:
 level:
  root: ERROR
  org.springframework.web: INFO
  com.sun.mail.smtp: INFO
  com.ssparser: INFO
ssparser:
  cronTime: "0 * * * * *"



